package film

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
 * DO NOT EDIT THIS FILE!! 
 * 
 *  TO CUSTOMIZE FilmBase.go PLEASE EDIT ./Film.go
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 * 
 */

import (
	"encoding/json"
	"net/http"

	"github.com/globalsign/mgo/bson"
	"github.com/go-chi/chi"
	"github.com/go-chi/render"
)

// Data model
type Film struct {
	ID		bson.ObjectId	`bson:"_id,omitempty" json:"_id"`
	Genre	string		`json:"genre"`
	Title	string		`json:"title"`
	Year	float32		`json:"year"`

	Cast	[]bson.ObjectId	`bson:"cast,omitempty" json:"cast"`
	FilmMaker	bson.ObjectId	`bson:"filmMaker,omitempty" json:"filmMaker"`

}

// Functions

// CRUD METHODS
	
// CRUD - CREATE
func (config *Config) create(writer http.ResponseWriter, req *http.Request) {

	var body Film
	json.NewDecoder(req.Body).Decode(&body)
	config.Database.C("Film").Insert(body)
	render.JSON(writer, req, &body)
}

// CRUD - DELETE
func (config *Config) delete(writer http.ResponseWriter, req *http.Request) {

	id := chi.URLParam(req, "id")
	config.Database.C("Film").RemoveId(bson.ObjectIdHex(id))
	render.JSON(writer, req, id)
}

// CRUD - FIND BY cast
func (config *Config) findBycast(writer http.ResponseWriter, req *http.Request) {
	var result []Film
	key := chi.URLParam(req, "key")
	err := config.Database.C("Film").Find(bson.M{"cast": bson.ObjectIdHex(key)}).All(&result)
	if err != nil {
		panic(err)
	}

	render.JSON(writer, req, result)
}

// CRUD - FIND BY filmMaker
func (config *Config) findByfilmMaker(writer http.ResponseWriter, req *http.Request) {
	var result []Film
	key := chi.URLParam(req, "key")
	err := config.Database.C("Film").Find(bson.M{"filmMaker": bson.ObjectIdHex(key)}).All(&result)
	if err != nil {
		panic(err)
	}

	render.JSON(writer, req, result)
}

// CRUD - GET
func (config *Config) get(writer http.ResponseWriter, req *http.Request) {

	var result Film
	id := chi.URLParam(req, "id")
	err := config.Database.C("Film").FindId(bson.ObjectIdHex(id)).One(&result)
	if err != nil {
		panic(err)
	}

	render.JSON(writer, req, result)
}
	
// CRUD - GET LIST
func (config *Config) list(writer http.ResponseWriter, req *http.Request) {

	var result []Film
	err := config.Database.C("Film").Find(nil).All(&result)
	if err != nil {
		panic(err)
	}

	render.JSON(writer, req, result)
}

// CRUD - UPDATE
func (config *Config) update(writer http.ResponseWriter, req *http.Request) {

	id := chi.URLParam(req, "id")
	var body Film
	json.NewDecoder(req.Body).Decode(&body)
	config.Database.C("Film").UpdateId(bson.ObjectIdHex(id), body)
	render.JSON(writer, req, body)
}

/*
 * CUSTOM SERVICES
 * 
 *	These services will be overwritten and implemented in  Ext.go
 */
